version: '3.9'

services:
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: skypro_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./my_dump.sql:/docker-entrypoint-initdb.d/my_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d skypro_database"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: skypro_backend
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate 
      && gunicorn -b 0.0.0.0:8000 SkyproProject.wsgi:application"
    ports:
      - '8888:8000'
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/mediafiles/
      - .env.docker:/app/.env

volumes:
  postgres_data:
  static_value:
  media_value: